
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x72460, LENGTH = 0xDBA0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x60400;
fifo_10_buff_0 = .;
. += 0x800;
. = 0x60C00;
fifo_10_buff_1 = .;
. += 0x800;
. = 0x61D60;
fifo_8_cons_buff_0 = .;
. += 0x380;
. = 0x620E0;
fifo_8_cons_buff_1 = .;
. += 0x380;
. = 0x61400;
fifo_6_cons_buff_0 = .;
. += 0x4B0;
. = 0x618B0;
fifo_6_cons_buff_1 = .;
. += 0x4B0;
. = 0x70400;
fifo_4_buff_0 = .;
. += 0x800;
. = 0x70C00;
fifo_4_buff_1 = .;
. += 0x800;
. = 0x71D60;
fifo_2_cons_buff_0 = .;
. += 0x380;
. = 0x720E0;
fifo_2_cons_buff_1 = .;
. += 0x380;
. = 0x71400;
fifo_0_cons_buff_0 = .;
. += 0x4B0;
. = 0x718B0;
fifo_0_cons_buff_1 = .;
. += 0x4B0;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_0_2);
