
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x76960, LENGTH = 0x96A0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x70400;
fifo_4_buff_0 = .;
. += 0x2000;
. = 0x72400;
fifo_4_buff_1 = .;
. += 0x2000;
. = 0x76260;
fifo_2_cons_buff_0 = .;
. += 0x380;
. = 0x765E0;
fifo_2_cons_buff_1 = .;
. += 0x380;
. = 0x74400;
fifo_0_cons_buff_0 = .;
. += 0xF30;
. = 0x75330;
fifo_0_cons_buff_1 = .;
. += 0xF30;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_0_2);
